name: Python Linting
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Run Ruff
        run: uv run ruff check --output-format=github . 
      - name: Generate SARIF output
        if: ${{ !cancelled() }}
        run: uv run ruff check --output-format=sarif . > ruff.sarif
      - name: Run ty
        if: ${{ !cancelled() }}
        run: uv run ty check --output-format=github .
      - name: Run pyrefly
        if: ${{ !cancelled() }}
        run: uv run pyrefly check --output-format=github .
      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v3
      - name: Upload SARIF file
        if: ${{ !cancelled() }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ruff.sarif